apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::774608100706:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OC5UAN1OIVR0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::774608100706:role/UdacityFlaskDeployCBKubectlRole
      username: build

  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-03T20:55:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1174"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 10a65409-7749-4e4c-9852-397da60dff81
