apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::774608100706:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OC5UAN1OIVR0
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::774608100706:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-02T06:45:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8351"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8d905312-18cd-4a1e-a201-20a0e578970a
